// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXvos5d2QVr9W54Tqzjz-cyaA6P9naHqA',
    appId: '1:740318188922:web:34fa8a12da0b46555d32c3',
    messagingSenderId: '740318188922',
    projectId: 'pizza-app-cb5ae',
    authDomain: 'pizza-app-cb5ae.firebaseapp.com',
    storageBucket: 'pizza-app-cb5ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc67czml13BFAy-8NWOJZ_0pExHGS0N-k',
    appId: '1:740318188922:android:e5a7e99c2589d0175d32c3',
    messagingSenderId: '740318188922',
    projectId: 'pizza-app-cb5ae',
    storageBucket: 'pizza-app-cb5ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMXxh3YmFsbAWHx9-MwbsZYtD0z3HrlhA',
    appId: '1:740318188922:ios:d970af2fc678b6615d32c3',
    messagingSenderId: '740318188922',
    projectId: 'pizza-app-cb5ae',
    storageBucket: 'pizza-app-cb5ae.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMXxh3YmFsbAWHx9-MwbsZYtD0z3HrlhA',
    appId: '1:740318188922:ios:d970af2fc678b6615d32c3',
    messagingSenderId: '740318188922',
    projectId: 'pizza-app-cb5ae',
    storageBucket: 'pizza-app-cb5ae.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXvos5d2QVr9W54Tqzjz-cyaA6P9naHqA',
    appId: '1:740318188922:web:aa7915df2a169c6d5d32c3',
    messagingSenderId: '740318188922',
    projectId: 'pizza-app-cb5ae',
    authDomain: 'pizza-app-cb5ae.firebaseapp.com',
    storageBucket: 'pizza-app-cb5ae.appspot.com',
  );
}
